### ISSUE TITLE
repl not working on osx

### ISSUE THREAD

**Issue by chrand** [LuxLang/lux#24]
osx 10.11, jdk 1.8.0_112. The first toy project in the book, chap. 1, works. REPL shows the following error at start (below, `../lux_test/..` is `../my_project/..`)
`$ lein lux repl` 

`$ java -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:-OmitStackTraceInFastThrow  -cp $HOME/.m2/repository/com/github/luxlang/luxc-jvm/0.5.0/luxc-jvm-0.5.0.jar:$HOME/.m2/repository/com/github/luxlang/stdlib/0.5.0/stdlib-0.5.0.jar:$HOME/.m2/repository/org/clojure/clojure/1.6.0/clojure-1.6.0.jar:$HOME/.m2/repository/org/clojure/core.match/0.2.1/core.match-0.2.1.jar:$HOME/.m2/repository/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar:$HOME/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar:$HOME/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar lux repl $HOME/tmp/lux_test/source`

> Exception in thread "main" clojure.lang.ArityException: Wrong number of args (0) passed to: compiler/init!
>  at clojure.lang.AFn.throwArity(AFn.java:429)
>  at clojure.lang.AFn.invoke(AFn.java:28)
  at lux.repl$init.invoke(repl.clj:28)
  at lux.repl$repl.invoke(repl.clj:55)
  at lux$_main$fn__29097$fn__29098.invoke(lux.clj:35)
  at lux$_main$fn__29097.invoke(lux.clj:27)
  at lux$_main.doInvoke(lux.clj:27)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at lux.main(Unknown Source)`

**Comment by LuxLang** [comment]
Yes.

A change in the way the compiler works now messed with the REPL and the error skipped me.

I'll re-release v0.5.0 with a quick patch for it later today.

**Comment by LuxLang** [comment]
I just released the patched version.

I re-released it as v0.5.0, to avoid causing inconvenience by making people have to change the version.

Try again with the REPL.

If you get the same error, clean the Maven cache at .m2 to make sure the lux-lein plugin downloads the Lux compiler again.

**Comment by chrand** [comment]
awesome, thank you :)
