### ISSUE TITLE
Vs. Typed Racket?

### ISSUE THREAD

**Issue by tliron** [LuxLang/lux#25]
Could you add a comparison to [Typed Racket](https://docs.racket-lang.org/ts-guide/)? What advantages to you see to Lux? Could you acknowledge advantages that Racket has?

**Comment by LuxLang** [comment]
Not a bad idea.

I'll see if I write a wiki page about that during the week.

**Comment by bsima** [comment]
Comparison to [Shen](http://shenlanguage.org/) would be interesting as well

**Comment by LuxLang** [comment]
> Comparison to Shen would be interesting as well

Also can do.

**Comment by LuxLang** [comment]
@tliron https://github.com/LuxLang/lux/wiki/Comparison-to-Typed-Racket
@bsima https://github.com/LuxLang/lux/wiki/Comparison-to-Shen

**Comment by tliron** [comment]
I had no idea that you needed to pay for Shen to get concurrency. Stunning and damning.

**Comment by bsima** [comment]
@tliron Tarver has a rather idiomatic perspective on OSS licensing: https://groups.google.com/forum/#!searchin/qilang/bsd%2420clause%7Csort:relevance/qilang/mVSJIyp-OhM/0XreitQq-ywJ

Idk if he's "correct" or "incorrect" necessarily, but at least that's some context for ya
