### ISSUE TITLE
Vs. Typed Clojure?

### ISSUE THREAD

**Issue by tliron** [LuxLang/lux#26]
What about a comparison to the [Typed Clojure](https://github.com/clojure/core.typed) project?

**Comment by LuxLang** [comment]
Also possible.

Fun fact: I began Lux, in part, out of frustration with Typed Clojure.

Should be fun to dismantle it.

**Comment by tliron** [comment]
:brings the popcorn:

**Comment by LuxLang** [comment]
Done:
https://github.com/LuxLang/lux/wiki/Comparison-to-Typed-Clojure
