### ISSUE TITLE
Vs. hackett

### ISSUE THREAD

**Issue by sirinath** [LuxLang/lux#27]
Would be interested to know how you stack against [Hackett](https://github.com/lexi-lambda/hackett)

**Comment by LuxLang** [comment]
I think Hackett is still too immature to go around picking fights with it.

For all I know, it may not even be around anymore within a year.

I don't want to be dismissive, but in the time I've been working on Lux, I've already seen a few languages that were more mature than Hackett get abandoned by their creators, so I want to wait a bit longer until I treat Hackett as an actual rival.

However, if you're fine with a quick summary of differences, here I go:

* Hackett's target platform is Racket. Lux's is "anything that could possibly run Lux" (i.e. JVM, JS runtimes, CLR, Python, Ruby, even native). I'm not sure if Hackett's author is thinking in a practical way about this choice...
* Hackett tries to be Haskell with parentheses. Lux tries to expose the innards of the compiler and the type-system to the users so they can make anything they want out of it.
* The Lux compiler is aware of Lux's type-system, but Hackett's type-system is based on meta-data and only works at the macro level. In some ways, this is a point in favor of Hackett, but I'm still not sure if Hackett's method can provide all the integration with the compiler that Lux demands.

With that said, I'm intrigued by Hackett's way of doing types, and I read the paper from which the author got the idea.

I'm currently thinking if there is some merit to switching to that system in the future, or if I'm better off sticking to what I have.

But currently, the only interesting thing Hackett has over Lux is that particular type-system design.
