### ISSUE TITLE
Add integration with dev tools

### ISSUE THREAD

**Issue by lostbean** [LuxLang/lux#40]
Modern compilers have very good integration with development tools and [Language Sever Protocol](http://langserver.org/) seems to be very helpful to lower the effort to support a variate of editors/IDEs.

**Comment by ahedgewitch** [comment]
Personally, something I'm going to be looking into is [Glamorous Toolkit](https://gtoolkit.com/). It's got the most support for Pharo (Smalltalk) atm, but that's also what it was written in. Its main advantage is that it's built from the ground up to not only be a code editor, but an analysis and visualization environment, as well. It also already has tools for analyzing Java and JavaScript code, so, I'm already envisioning an environment where users could analyze their Lux code and the resultant output *simultaneously* in a visual manner and am quite interested in trying to make that happen.

**Comment by eduardoejp** [comment]
@ahedgewitch 
I've never heard of Glamorous Toolkit, but you sold me with Phato/Smalltalk.

If this is good enough for the smalltalk people, it's good enough for me.

I don't have a lot of cycles to spare on this ATM, but I'm definitely looking into it in the future.

**Comment by ahedgewitch** [comment]
https://zed.dev/

Another editor to keep an eye on.

**Comment by eduardoejp** [comment]
* https://microsoft.github.io/debug-adapter-protocol/
* https://www.chris-kipp.io/blog/the-debug-adapter-protocol-and-scala
* https://build-server-protocol.github.io/
*
