### ISSUE TITLE
Commercial License?

### ISSUE THREAD

**Issue by rschmukler** [LuxLang/lux#55]
My understanding is that the lack of commercial use means that:

1) A company could not build software written in Lux that they intended to sell.
2) A company could not use software written in Lux internally to help them operate their business.

Am I interpreting this correctly?

Do you intend to allow commercial use at some point in the future? Do you intend to sell licenses to it in the future? If not, any information as to why you made this choice? Obviously you can do whatever you want with it, and I appreciate you open-sourcing it at all - but I am curious.

**Comment by eduardoejp** [comment]
Apologies for not answering earlier.

I thought the "Watching" option for this repo would notify me whenever someone opened a new issue, but that doesn't appear to be the case.

I'll have to find some way to always get notified.

Anyhow...

> My understanding is that the lack of commercial use means that:
> 
> 1. A company could not build software written in Lux that they intended to sell.
> 1. A company could not use software written in Lux internally to help them operate their business.
> 
> Am I interpreting this correctly?

Yes.

> Do you intend to allow commercial use at some point in the future? Do you intend to sell licenses to it in the future?

I do intend to sell commercial licenses for v0.6.
Currently, I'm just focusing on finishing v0.6.

**Comment by rschmukler** [comment]
Awesome! Happy to hear that you will be facilitating commercial use at some point. Good luck w/ v0.6!
