### ISSUE TITLE
gitter channel

### ISSUE THREAD

**Issue by fommil** [LuxLang/lux#6]
Running a free software community, you'll benefit from a https://gitter.im channel. It's much easier for people to start a discussion there than mailing lists. In ENSIME, we've found that much more people engage with us through the issue tracker, twitter and gitter than the mailing list.

**Comment by LuxLang** [comment]
Sweet. I'll take a look as soon as I've got some free time.

**Comment by LuxLang** [comment]
There is now a Gitter group for Lux.
