### ISSUE TITLE
how to manual install ?

### ISSUE THREAD

**Issue by WingDust** [LuxLang/lux#69]
my terminal  network is so bad to download 
```sh
com.github.luxlang:lux-jvm-0.7.0
com.github.luxlang:stdlib-0.7.0
```
how to manual install this thing ?

**Comment by eduardoejp** [comment]
Extract the following zip files in your `~/.m2/repository/com/github/luxlang/` directory.

[lux-jvm.zip](https://github.com/LuxLang/lux/files/12386233/lux-jvm.zip)
[lux-jvm-function.zip](https://github.com/LuxLang/lux/files/12386235/lux-jvm-function.zip)
[stdlib.zip](https://github.com/LuxLang/lux/files/12386236/stdlib.zip)

**Comment by WingDust** [comment]
@eduardoejp  anther question how to log any type var ?
```lisp
(.require
 [library
  [lux (.except)
   [program (.only program)]
   ["[0]" debug]
   [control
    ["[0]" io]]]])

(def main
  (program args
    (io.io (debug.log! #testlog ))))
```

**Comment by eduardoejp** [comment]
@WingDust Import the `library/lux/data/text/format` module. It offers several functions for text-formatting of different types.

https://github.com/LuxLang/lux/blob/master/documentation/library/standard/jvm.md#libraryluxdatatextformat
