### ISSUE TITLE
code of conduct?

### ISSUE THREAD

**Issue by fommil** [LuxLang/lux#7]
If you're building a community, I recommend putting one in place. In ENSIME, we welcome contributors with this page https://github.com/ensime/ensime-server/blob/master/CONTRIBUTING.md which leads to https://github.com/ensime/ensime-server/wiki/Code-of-Conduct

It's really good to have one in place just incase a bad apple comes along, who destroys everything that you've worked for.

**Comment by fommil** [comment]
(FYI, a lack of Code of Conduct almost killed Scala back in the early days)

**Comment by LuxLang** [comment]
I'm not big on the whole idea of codes of conduct, as I don't like policing people's behavior (that often devolves into policing their opinions and then that devolves into kicking out those who refuse to drink the Kool-Aid).

With that said, I'll take a look into it and maybe I can come up with a code of conduct that's lightweight, yet effective.

**Comment by fommil** [comment]
That's basically what we did too... we just used an existing tried and tested CoC instead of writing one from scratch. The big trigger for me was realising that people weren't contributing because we didn't have a CoC. I've never heard of anybody not contributing because there is a CoC (unless they were the bad apple). Better to be safe than sorry.

**Comment by LuxLang** [comment]
Adopted the **Contributor Covenant** as the project's code of conduct.
http://contributor-covenant.org/

**Comment by fommil** [comment]
:smile:
